# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
#  database: hspace_development
  pool: 5
#  username: myapp
#  password: password1


development:
  <<: *default